// Copyright 2021 Illumio, Inc. All Rights Reserved.

package main

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"strconv"
	"strings"

	"github.com/Jeffail/gabs/v2"
	"github.com/illumio/terraform-provider-illumio-core/client"
	"github.com/illumio/terraform-provider-illumio-core/models"
	"golang.org/x/time/rate"
)

const (
	// hrefs.csv is generated by terraform-provider-illumio-core.
	// Each line is "resource_type,href"; the resource type is advisory and
	// retained for backward compatibility, while the href is authoritative.
	filename = "hrefs.csv"

	// secPolicySegment marks the start of a security policy object path.
	// Only objects below it can be provisioned.
	secPolicySegment = "sec_policy"
)

// hrefEntry is one provisionable policy object read from the href file.
type hrefEntry struct {
	// ResourceType is the change-subset collection name, always derived from
	// Href rather than read from the file.
	ResourceType string
	Href         string
	Line         int
}

// resourceTypeFromHref derives the security policy change-subset collection
// name from a policy object href.
//
//	/orgs/1/sec_policy/draft/rule_sets/3            -> rule_sets
//	/orgs/1/sec_policy/draft/firewall_settings      -> firewall_settings
//	/orgs/1/sec_policy/draft/rule_sets/3/sec_rules/5 -> rule_sets
//
// Nested objects such as sec rules and deny rules resolve to their parent rule
// set, which is the object the PCE actually provisions.
//
// Deriving the type from the href removes the need for a hardcoded list of
// known resource types: a policy object type this binary has never heard of is
// handled correctly, instead of being dropped with a warning.
func resourceTypeFromHref(href string) (string, error) {
	trimmed := strings.Trim(strings.TrimSpace(href), "/")
	if trimmed == "" {
		return "", errors.New("empty href")
	}

	parts := strings.Split(trimmed, "/")
	for i, part := range parts {
		if part != secPolicySegment {
			continue
		}
		// parts[i+1] is the policy version, parts[i+2] is the collection name.
		if i+2 >= len(parts) || parts[i+2] == "" {
			return "", fmt.Errorf("href %q ends at the policy version and names no policy object", href)
		}
		return parts[i+2], nil
	}

	return "", fmt.Errorf("href %q is not a security policy object (no %q path segment); only security policy objects can be provisioned", href, secPolicySegment)
}

// parseHrefFile reads href entries, returning one error per unusable line
// rather than skipping it silently or panicking.
//
// Duplicate hrefs are collapsed, preserving first-seen order.
func parseHrefFile(r io.Reader) ([]hrefEntry, []error) {
	var (
		entries []hrefEntry
		errs    []error
		seen    = map[string]bool{}
		lineNo  int
	)

	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}

		// Hrefs never contain a comma, so the final field is always the href.
		// This also tolerates a bare href with no leading resource-type column.
		fields := strings.Split(line, ",")
		href := strings.TrimSpace(fields[len(fields)-1])
		if href == "" {
			errs = append(errs, fmt.Errorf("line %d: no href in %q", lineNo, line))
			continue
		}

		rtype, err := resourceTypeFromHref(href)
		if err != nil {
			errs = append(errs, fmt.Errorf("line %d: %w", lineNo, err))
			continue
		}

		if seen[href] {
			continue
		}
		seen[href] = true
		entries = append(entries, hrefEntry{ResourceType: rtype, Href: href, Line: lineNo})
	}

	if err := scanner.Err(); err != nil {
		errs = append(errs, fmt.Errorf("reading %s: %w", filename, err))
	}

	return entries, errs
}

// collectPendingHrefs returns the set of hrefs in a GET /sec_policy/pending
// response.
//
// It walks every key in the response rather than a fixed allowlist, so policy
// object types added by future PCE versions are discovered automatically.
// Collections arrive as arrays of objects; singletons such as
// firewall_settings arrive as a bare object.
func collectPendingHrefs(data *gabs.Container) map[string]bool {
	pending := map[string]bool{}
	if data == nil {
		return pending
	}

	for _, value := range data.ChildrenMap() {
		switch value.Data().(type) {
		case []interface{}:
			for _, child := range value.Children() {
				if href, ok := child.S("href").Data().(string); ok && href != "" {
					pending[href] = true
				}
			}
		case map[string]interface{}:
			if href, ok := value.S("href").Data().(string); ok && href != "" {
				pending[href] = true
			}
		}
	}

	return pending
}

func main() {
	os.Exit(run())
}

// run performs provisioning and returns the process exit code. It is separate
// from main so that every failure path returns a non-zero status: the previous
// implementation warned about skipped hrefs and still exited 0, so a policy
// change could silently fail to provision.
func run() int {
	file, err := os.Open(filename)
	if err != nil {
		if os.IsNotExist(err) {
			// The provider only writes the file when it touches a versioned
			// policy object, so its absence means there was nothing to
			// provision. That is a success, not a failure: otherwise
			// "terraform apply && provision" fails on every apply that
			// changed no policy objects.
			log.Printf("[INFO] No %s found - nothing to provision", filename)
			return 0
		}
		log.Printf("[ERROR] Error opening file %s: %v", filename, err)
		return 1
	}
	defer file.Close()

	entries, parseErrs := parseHrefFile(file)
	if len(parseErrs) > 0 {
		for _, e := range parseErrs {
			log.Printf("[ERROR] %s: %v", filename, e)
		}
		// Refuse to provision a partial change subset. The file is left in
		// place so the run can be retried once the bad lines are corrected.
		log.Printf("[ERROR] %d unusable line(s) in %s; nothing was provisioned", len(parseErrs), filename)
		return 1
	}

	if len(entries) == 0 {
		log.Printf("[INFO] No hrefs in %s - nothing to provision", filename)
		return removeHrefFile()
	}

	// Only contact the PCE once there is something to do, so credentials are
	// not required for a no-op run.
	illumioV2Client, err := newClientFromEnv()
	if err != nil {
		log.Printf("[ERROR] %v", err)
		return 1
	}

	orgID := illumioV2Client.OrgID
	_, cont, err := illumioV2Client.Get(fmt.Sprintf("/orgs/%d/sec_policy/pending", orgID), nil)
	if err != nil {
		log.Printf("[ERROR] Error fetching pending security policy: %v", err)
		return 1
	}
	pending := collectPendingHrefs(cont)

	changeSubset := models.NewSecurityPolicyChangeSubset()
	for _, entry := range entries {
		if !pending[entry.Href] {
			// Benign: the object has no pending change, because it was already
			// provisioned or was created and deleted within the same apply.
			log.Printf("[INFO] No pending change for %s - skipping", entry.Href)
			continue
		}
		log.Printf("[DEBUG] ResourceType: %s, HREF: %s", entry.ResourceType, entry.Href)
		if err := changeSubset.AppendHref(entry.ResourceType, entry.Href); err != nil {
			log.Printf("[ERROR] line %d: %v", entry.Line, err)
			return 1
		}
	}

	if changeSubset.Size() > 0 {
		secPolicy := &models.SecurityPolicy{
			UpdateDesc:   "Provisioned by terraform",
			ChangeSubset: changeSubset,
		}
		_, data, err := illumioV2Client.Create(fmt.Sprintf("/orgs/%d/sec_policy", orgID), secPolicy)
		if err != nil {
			// Leave the file in place so the run can be retried.
			log.Printf("[ERROR] Error during provisioning: %v", err)
			return 1
		}
		log.Printf("[DEBUG] Provisioning response: %v", data)
		log.Printf("[INFO] Provisioned %d object(s)", changeSubset.Size())
	} else {
		log.Print("[INFO] No changes to provision")
	}

	return removeHrefFile()
}

// removeHrefFile deletes the processed href file, returning an exit code.
//
// A leftover file is reprocessed on the next run, so a failed removal is
// reported as an error rather than a warning - but the message states
// explicitly that provisioning itself succeeded, so the operator knows the
// policy is active and only the bookkeeping needs attention.
func removeHrefFile() int {
	if err := os.Remove(filename); err != nil {
		log.Printf("[ERROR] Provisioning succeeded, but %s could not be removed: %v", filename, err)
		log.Printf("[ERROR] Remove it manually to avoid reprocessing these hrefs")
		return 1
	}
	return 0
}

// newClientFromEnv builds a PCE client from the ILLUMIO_* environment.
func newClientFromEnv() (*client.V2, error) {
	pceHost := os.Getenv("ILLUMIO_PCE_HOST")
	apiKeyUsername := os.Getenv("ILLUMIO_API_KEY_USERNAME")
	apiKeySecret := os.Getenv("ILLUMIO_API_KEY_SECRET")
	if pceHost == "" || apiKeyUsername == "" || apiKeySecret == "" {
		return nil, errors.New(`missing a required environment variable.
Please set ILLUMIO_PCE_HOST, ILLUMIO_API_KEY_USERNAME, ILLUMIO_API_KEY_SECRET`)
	}

	orgID, err := strconv.Atoi(os.Getenv("ILLUMIO_PCE_ORG_ID"))
	if err != nil {
		orgID = 1
	}

	return client.NewV2(
		pceHost,
		orgID,
		apiKeyUsername,
		apiKeySecret,
		30,
		rate.NewLimiter(rate.Limit(float64(125)/float64(60)), 1), // limits API calls 125/min
		10,
		3,
		os.Getenv("ILLUMIO_ALLOW_INSECURE_TLS") == "yes",
		os.Getenv("ILLUMIO_CA_FILE"),
		os.Getenv("ILLUMIO_PROXY_URL"),
		os.Getenv("ILLUMIO_PROXY_CREDENTIALS"),
	)
}
